[[redirects]]
from = "/auth/login"
to = "http://15.165.223.121:8080/auth/login"
status = 200
force = true

[[redirects]]
from = "/api/members/step1"
to = "http://15.165.223.121:8080/api/members/step1"
status = 200
force = true
